require('core.plugin-config.nvim-tree')
require('core.plugin-config.telescope')
require('core.plugin-config.nvim-treesitter')
require('core.plugin-config.lualine')
require('core.plugin-config.indent-blankline')
require('core.plugin-config.lsp')
require('core.plugin-config.prettier')
require('core.plugin-config.nvim-cmp')
require('core.plugin-config.trouble')
require('core.plugin-config.which-key')
require('core.plugin-config.git')

